name: Test Artifact
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
      - name: init cache

        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ./vite-project/.npm
      - name: Install dependencies
        working-directory: ./vite-project
        run: npm ci --cache .npm
      - name: Build application
        working-directory: ./vite-project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./vite-project/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - run: |
          ls
          ls ./build
