name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: set_fruit
        run: echo fruit=pomme >> "$GITHUB_OUTPUT"

      - id: check_fruit
        run: echo ::error::fruit is ${{ steps.set_fruit.outputs.fruit }} but should be poire
        if: steps.set_fruit.outputs.fruit != 'poire'
