name: Résumé Github
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_STEP_SUMMARY
      - run: |
          echo "# Résumé de notre Github actions" >> $GITHUB_STEP_SUMMARY
          echo "## Préparation au décollage" >> $GITHUB_STEP_SUMMARY
          echo "décollage immédiat :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- 3" >> $GITHUB_STEP_SUMMARY
          echo "- 2" >> $GITHUB_STEP_SUMMARY
          echo "- 1" >> $GITHUB_STEP_SUMMARY
          echo "- décollage réussi" >> $GITHUB_STEP_SUMMARY
