name: Test Docker
on: push

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
          node -v
