name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::notice::Un message d'info"
      - run: echo "::warning::Un warning"
      - run: echo "::error::Une erreur"
