name: Injection Script
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      titre: ${{ github.event.head_commit.message }}
    steps:
      - run: |
          echo $titre
          echo Hello world !
