name: Vérification du fruit
on: push

jobs:
  check-fruit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lire le fruit
        id: lire_fruit
        run: |
          fruit=$(cat fruit.txt)
          echo "fruit=$fruit" >> "$GITHUB_OUTPUT"

      - name: Vérification du fruit
        if: steps.lire_fruit.outputs.fruit != 'poire'
        run: |
          echo "::error file=fruit.txt,line=1::Le fruit n'est pas correct, attendu: poire"
