name: Mon premier workflow
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ 42 }}
      # bien sur oco on récupère plustot en général des contexte ou des variables
      # montrer des exemples concret
      - run: echo main = top ? ${{ 'main' == 'top'}}
      - run: echo la branche actuelle contient elle main ? ${{ contains(github.ref, 'main')}}
