name: Mon premier workflow
on: [push]
env:
  NAME_STEP: STEP One
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      #     - name: $NAME_STEP
      - name: ${{ env.NAME_STEP}}
        run: |
          echo NAME_STEP: $NAME_STEP
