name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: wait-for-previous
      cancel-in-progress: true
    steps:
      - run: |
          echo Very long step

          sleep 100
          echo done !
