name: Mon premier workflow
on:
  push:
    branches:
      - main
    # - feature
    # branches-ignore:
    #   - main
    paths:
      - "!docs/**"
      - "**.png"
    # paths-ignore:
    #   - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo traitement image
