name: Test Docker
on: push

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
    container:
      image: node:18
    steps:
      - name: Installer Redis CLI
        run: apt update && apt install -y redis-tools
      - name: tester la connexion à Redis
        run: redis-cli -h redis ping
