name: Mon premier workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo github_env: $GITHUB_ENV
          echo FROM_STEP_1=value_step_1 >> $GITHUB_ENV
      - id: step2
        run: |
          echo github_env step2: $GITHUB_ENV
          echo FROM_STEP_1: $FROM_STEP_1
          echo FROM env:  ${{ env.FROM_STEP_1 }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - run: echo deploy in prod
