name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: wait-for-previous
    steps:
      - run: |
          echo Very long step

          sleep 100
          echo done !
