name: Test Docker
on: push

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Installer Redis CLI
        run: sudo apt update && sudo apt install -y redis-tools
      - name: tester la connexion à Redis
        run: redis-cli -h localhost -p 6379 ping
